apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-hello-world-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubernetes-hello-world
  template:
    metadata:
      labels:
        app: kubernetes-hello-world
    spec:
      containers:
      - name: kubernetes-hello-world-container
        image: alensden2/kube-hello-world:tag1
        ports:
        - containerPort: 3000