apiVersion: v1
kind: Service
metadata:
  name: kubernetes-hello-world-service
spec:
  selector:
    app: kubernetes-hello-world
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer